import dev.echoellet.minecraft_safe_resources.GenerateJsonKeysTask
import dev.echoellet.minecraft_safe_resources.OutputLanguage

plugins {
    `java-library`
    id("net.neoforged.moddev").version("2.0.120")
    idea
    id("me.modmuss50.mod-publish-plugin").version("1.1.0")
    id("dev.echoellet.minecraft-safe-resources") version ("0.0.1")
}

tasks.named<Wrapper>("wrapper") {
    distributionType = Wrapper.DistributionType.BIN
}

val modVersion = gradleProperty("mod_version")
val mcVersion = gradleProperty("minecraft_version")
val neoforgeVersion = gradleProperty("neo_version")
val modId = gradleProperty("mod_id")
val modLoader = "neoforge"
val modGroupId = gradleProperty("mod_group_id")

version = modVersion
group = modGroupId

repositories {
    fun strictMaven(name: String, url: String, vararg includeGroups: String) {
        exclusiveContent {
            forRepository { maven { this.name = name; this.url = uri(url) } }
            filter {
                includeGroups.forEach { includeGroup(it) }
            }
        }
    }
    flatDir { dir("libs") }

    strictMaven("CurseForge", "https://cursemaven.com", "curse.maven")
    strictMaven("Modrinth", "https://api.modrinth.com/maven", "maven.modrinth")

    // JEI
    strictMaven("Jared", "https://maven.blamejared.com", "mezz.jei")
    strictMaven("Architectury", "https://maven.architectury.dev", "dev.architectury")

    // KubeJS
    strictMaven("Latvian", "https://maven.latvian.dev/releases", "dev.latvian.mods")

    // Controlify, YACL
    strictMaven("IsXander", "https://maven.isxander.dev/releases", "dev.isxander")
    strictMaven("AzureDoom Mods", "https://maven.azuredoom.com/mods", "mod.azure.azurelib", "mod.azure.azurelibarmor")
    strictMaven("GeckoLib", "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/", "software.bernie.geckolib")
}

base {
    archivesName = modId
    version = getFullModVersion()
}

fun getFullModVersion(): String = "${modVersion}-mc${mcVersion}-${modLoader}"

java {
    withSourcesJar()

    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

val sourcesJar by tasks.getting(Jar::class)

neoForge {
    version = neoforgeVersion

    parchment {
        mappingsVersion = gradleProperty("parchment_mappings_version")
        minecraftVersion = mcVersion
    }

    runs {
        create("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            data()
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by NeoForge's data generators.
sourceSets.main {
    resources.srcDir(layout.projectDirectory.dir("src/generated/resources"))
}

configurations {
    val localRuntime by creating

    runtimeClasspath {
        extendsFrom(localRuntime)
    }
}

fun gradleProperty(name: String): String {
    return providers.gradleProperty(name).get()
}

dependencies {
    val localRuntime by configurations.getting

    // JEI compatibility
    val jeiVersion = gradleProperty("jei_version")
    compileOnly("mezz.jei:jei-${mcVersion}-common-api:${jeiVersion}")
    compileOnly("mezz.jei:jei-${mcVersion}-neoforge-api:${jeiVersion}")
    localRuntime("mezz.jei:jei-${mcVersion}-neoforge:${jeiVersion}")

    // Azurelib, Azurelib armor, Geckolib compatibility
    compileOnly("mod.azure.azurelib:azurelib-neo-${mcVersion}:${gradleProperty("azurelib_version")}")
    compileOnly("mod.azure.azurelibarmor:azurelibarmor-common-${mcVersion}:${gradleProperty("azurelib_armor_version")}")
    compileOnly("software.bernie.geckolib:geckolib-neoforge-${mcVersion}:${gradleProperty("geckolib_bersion")}")

    // Iris, Sodium, and compute shader compatibility
    compileOnly("curse.maven:irisshaders-455508:6661598")
    compileOnly("curse.maven:sodium-394468:6382651")

    // Werewolves, Vampirism compatibility, baking layer model for vampire and visibility fix when transform to the wolf
    compileOnly("curse.maven:werewolves-become-a-beast-417851:6538693")
    compileOnly("curse.maven:vampirism-become-a-vampire-233029:6544569")

    // Curios compatibility, baking curio models from curio slots
    compileOnly("curse.maven:curios-309927:6529130")

    // Player animator compatibility, emote fix
    compileOnly("curse.maven:playeranimator-658587:6024462")

    // KubeJS compatibility
    compileOnly("dev.latvian.mods:kubejs-neoforge:${gradleProperty("kubejs_version")}")
    compileOnly("dev.latvian.mods:rhino-neoforge:${gradleProperty("rhino_version")}")
    compileOnly("dev.architectury:architectury-neoforge:${gradleProperty("architectury_version")}")

    // Libraries for tr7zw featured mods (when you dependent your project on 3D Skin Layers or First-person)
    compileOnly("libs:TRansition:1.0.6")
    compileOnly("libs:TRender:1.0.7")

    // Skinlayer3d compatibility
    compileOnly("maven.modrinth:3dskinlayers:B7MZQ4xS")

    // First-person compatibility
    compileOnly("maven.modrinth:first-person-model:QWJDSZiH") // 2.5.0

    // Shoulder Surfing Reloaded compatibility (uncomment the runtimeOnly to test the mod)
    compileOnly("curse.maven:shoulder-surfing-reloaded-243190:6993797") // API only
    //runtimeOnly "curse.maven:shoulder-surfing-reloaded-243190:6993795" // Full mod JAR file

    // Controlify (controller support) compatibility.
    // Change "compileOnly" to "implementation" for testing in-game.
    compileOnly("dev.isxander:controlify:${gradleProperty("controlify_version")}") {
        // Only need Controlify API, ignore the transitive dependencies (e.g, QuiltMC parsers)
        isTransitive = false
    }
}

val generationTaskGroup = "generation"

val generateModMetadata by tasks.registering(ProcessResources::class) {
    group = generationTaskGroup

    val replaceProperties = mapOf(
        "minecraft_version_range" to gradleProperty("minecraft_version_range"),
        "neo_version_range" to gradleProperty("neo_version_range"),
        "loader_version_range" to gradleProperty("loader_version_range"),
        "mod_id" to modId,
        "mod_version" to modVersion,
        "mod_license" to gradleProperty("mod_license"),
        "mod_name" to gradleProperty("mod_name"),
        "mod_authors" to gradleProperty("mod_authors"),
        "mod_description" to gradleProperty("mod_description"),
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources.srcDir(generateModMetadata.map { it.outputs.files.singleFile })
}
neoForge.ideSyncTask(generateModMetadata)

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

val modAssetsDirPath = "src/main/resources/assets/$modId"

val generateLangKeys = tasks.register<GenerateJsonKeysTask>("generateLangKeys") {
    val enUsResourcePath = "$modAssetsDirPath/lang/en_us.json"

    inputResourceFile.set(project.file(enUsResourcePath))
    outputClassName.set("LangKeys")
    outputLanguage.set(OutputLanguage.JAVA)
    outputClassDescription.set(buildString {
        append("A generated object that represents the keys in `$enUsResourcePath` resource file,"); appendLine()
        append("to avoid hardcoding the keys across the codebase, which is error-prone, inefficient, and less type-safe.")
        appendLine(); appendLine()
        append("**Note:** Breaking changes may occur. This approach is preferred over hardcoding keys, which can lead to runtime errors or crashes.")
    })
    outputPackage.set("$modGroupId.generated")
    keyNamespaceToStrip.set(modId)
}

java.sourceSets.main.get().apply {
    java.srcDir(generateLangKeys.map { it.outputs.files.singleFile })
}

tasks.compileJava {
    dependsOn(generateLangKeys)
}

// The API JAR file includes only classes from the API package.

val apiPackage = "yesman/epicfight/api/**"
val apiJarClassifier = "api"

val apiJar by tasks.registering(Jar::class) {
    group = "build"
    archiveClassifier.set(apiJarClassifier)

    from(sourceSets.main.get().output) { include(apiPackage) }
}

val apiSourcesJar by tasks.registering(Jar::class) {
    group = "build"
    archiveClassifier.set("$apiJarClassifier-sources") // Important to use this suffix, to follow standards

    from(sourceSets.main.get().allSource) { include(apiPackage) }
}

artifacts {
    archives(apiJar)
    archives(apiSourcesJar)
}

fun extractCurrentVersionChangelog(): String? {
    val changelogFile = project.file("CHANGELOG.md")
    val fullChangelogText = changelogFile.readText()

    // Extracts the current version changelog without the version heading 2 and "For Devs" heading 3.
    val versionSectionRegex =
        "(?s)## \\[$modVersion\\] - \\d{4}-\\d{2}-\\d{2}\\R(.*?)(?=\\R### For Devs|\\R## \\[.*?\\] |\\Z)"
    val matcher = Regex(versionSectionRegex).find(fullChangelogText) ?: return null

    val versionChangelog = matcher.groupValues[1]
    return versionChangelog
}

fun buildReleaseChangelog(currentVersionChangelog: String): String {
    return buildString {
        append(currentVersionChangelog)
        appendLine(); appendLine()
        append(
            """
    ### **Tested against:**
    - **NeoForge:** $neoforgeVersion
    - **Minecraft:** $mcVersion
    """.trimIndent()
        )
    }
}

publishMods {
    dryRun.set(false)

    val latestChangelog = extractCurrentVersionChangelog() ?: run {
        error("No changelog found for version $modVersion in CHANGELOG.md file")
        return@publishMods
    }
    val releaseChangelog = buildReleaseChangelog(latestChangelog)
    changelog.set(releaseChangelog)

    modLoaders.add(modLoader)
    type.set(STABLE)
    displayName.set(getFullModVersion())
    file.set(tasks.jar.get().archiveFile)
    additionalFiles.from(sourcesJar, apiJar, apiSourcesJar)

    curseforge {
        accessToken.set(providers.environmentVariable("CURSEFORGE_TOKEN"))
        projectId.set("405076")
        minecraftVersions.add(mcVersion)
        projectSlug.set("epic-fight-mod") // Required for Discord notification
    }

    modrinth {
        accessToken.set(providers.environmentVariable("MODRINTH_TOKEN"))
        projectId.set("vu3NZ5Ma")
        minecraftVersions.add(mcVersion)

        // Syncs the GitHub README with the Modrinth project description
        projectDescription.set(
            providers.fileContents(layout.projectDirectory.file("README.md")).asText
        )
    }

    discord {
        webhookUrl.set(providers.environmentVariable("DISCORD_WEBHOOK"))
        dryRunWebhookUrl.set(providers.environmentVariable("DRY_RUN_DISCORD_WEBHOOK"))
        username.set("Update Notification")
        avatarUrl.set("https://i.imgur.com/FrxDviN.png")
        content.set(
            changelog.map {
                "<@&1074034800849059930>\n# Epic Fight $modVersion is out!\n- **Minecraft version:** ${mcVersion}\n- **NeoForge version:** ${neoforgeVersion}\n$latestChangelog"
            }
        )

        style {
            look.set("MODERN")
            link.set("EMBED")
            thumbnailUrl.set("https://i.imgur.com/nI8xOCy.png")
        }
    }
}
