import com.google.gson.JsonParser

plugins {
    `java-library`
    id("net.neoforged.moddev").version("2.0.120")
    idea
    id("me.modmuss50.mod-publish-plugin").version("1.1.0")
}

tasks.named<Wrapper>("wrapper") {
    distributionType = Wrapper.DistributionType.BIN
}

val modVersion = providers.gradleProperty("mod_version").get()
val mcVersion = providers.gradleProperty("minecraft_version").get()
val neoforgeVersion = providers.gradleProperty("neo_version").get()
val modId = providers.gradleProperty("mod_id").get()
val modLoader = "neoforge"
val modGroupId = providers.gradleProperty("mod_group_id").get()

version = modVersion
group = modGroupId

repositories {
    fun strictMaven(url: String, includeGroup: String, name: String? = null) {
        exclusiveContent {
            forRepository { maven { name?.let { this.name = it }; this.url = uri(url) } }
            filter { includeGroup(includeGroup) }
        }
    }
    flatDir { dir("libs") }

    strictMaven("https://cursemaven.com", "curse.maven", "CurseForge")
    strictMaven("https://api.modrinth.com/maven", "maven.modrinth", "Modrinth")

    // JEI
    strictMaven("https://maven.blamejared.com", "mezz.jei", "Jared")
    strictMaven("https://maven.architectury.dev", "dev.architectury", "Architectury")
    // KubeJS
    strictMaven("https://maven.latvian.dev/releases", "dev.latvian.mods", "Latvian")
    // Controlify, YACL
    strictMaven("https://maven.isxander.dev/releases", "dev.isxander", "IsXander")
}

base {
    archivesName = modId
    version = getFullModVersion()
}

fun getFullModVersion(): String = "${modVersion}-mc${mcVersion}-${modLoader}"

java {
    withSourcesJar()

    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

val sourcesJar by tasks.getting(Jar::class)

neoForge {
    version = neoforgeVersion

    parchment {
        mappingsVersion = providers.gradleProperty("parchment_mappings_version").get()
        minecraftVersion = mcVersion
    }

    runs {
        create("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            data()
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by NeoForge's data generators.
sourceSets.main {
    resources.srcDir(layout.projectDirectory.dir("src/generated/resources"))
}

configurations {
    val localRuntime by creating

    runtimeClasspath {
        extendsFrom(localRuntime)
    }
}

dependencies {
    val localRuntime by configurations.getting

    // JEI compatibility
    val jeiVersion = providers.gradleProperty("jei_version").get()
    compileOnly("mezz.jei:jei-${mcVersion}-common-api:${jeiVersion}")
    compileOnly("mezz.jei:jei-${mcVersion}-neoforge-api:${jeiVersion}")
    localRuntime("mezz.jei:jei-${mcVersion}-neoforge:${jeiVersion}")

    // Azurelib, Azurelib armor, Geckolib compatibility
    compileOnly("curse.maven:azurelib-817423:7084472")
    compileOnly("curse.maven:azurelib-armor-912767:7084466")
    compileOnly("curse.maven:geckolib-388172:6304958")

    // Iris, Sodium, and compute shader compatibility
    compileOnly("curse.maven:irisshaders-455508:6661598")
    compileOnly("curse.maven:sodium-394468:6382651")

    // Werewolves, Vampirism compatibility, baking layer model for vampire and visibility fix when transform to the wolf
    compileOnly("curse.maven:werewolves-become-a-beast-417851:6538693")
    compileOnly("curse.maven:vampirism-become-a-vampire-233029:6544569")

    // Curios compatibility, baking curio models from curio slots
    compileOnly("curse.maven:curios-309927:6529130")

    // Player animator compatibility, emote fix
    compileOnly("curse.maven:playeranimator-658587:6024462")

    // KubeJS compatibility
    compileOnly("dev.latvian.mods:kubejs-neoforge:${providers.gradleProperty("kubejs_version").get()}")
    compileOnly("dev.latvian.mods:rhino-neoforge:${providers.gradleProperty("rhino_version").get()}")
    compileOnly("dev.architectury:architectury-neoforge:${providers.gradleProperty("architectury_version").get()}")

    // Libraries for tr7zw featured mods (when you dependent your project on 3D Skin Layers or First-person)
    compileOnly("libs:TRansition:1.0.6")
    compileOnly("libs:TRender:1.0.7")

    // Skinlayer3d compatibility
    compileOnly("maven.modrinth:3dskinlayers:B7MZQ4xS")

    // First-person compatibility
    compileOnly("maven.modrinth:first-person-model:QWJDSZiH") // 2.5.0

    // Shoulder Surfing Reloaded compatibility (uncomment the runtimeOnly to test the mod)
    compileOnly("curse.maven:shoulder-surfing-reloaded-243190:6993797") // API only
    //runtimeOnly "curse.maven:shoulder-surfing-reloaded-243190:6993795" // Full mod JAR file

    // Controlify (controller support) compatibility.
    // Change "compileOnly" to "implementation" for testing in-game.
    compileOnly("dev.isxander:controlify:${providers.gradleProperty("controlify_version").get()}") {
        // Only need Controlify API, ignore the transitive dependencies (e.g, QuiltMC parsers)
        isTransitive = false
    }
}

val generationTaskGroup = "generation"

val generateModMetadata by tasks.registering(ProcessResources::class) {
    group = generationTaskGroup

    val replaceProperties = mapOf(
        "minecraft_version_range" to providers.gradleProperty("minecraft_version_range").get(),
        "neo_version_range" to providers.gradleProperty("neo_version_range").get(),
        "loader_version_range" to providers.gradleProperty("loader_version_range").get(),
        "mod_id" to modId,
        "mod_version" to modVersion,
        "mod_license" to providers.gradleProperty("mod_license").get(),
        "mod_name" to providers.gradleProperty("mod_name").get(),
        "mod_authors" to providers.gradleProperty("mod_authors").get(),
        "mod_description" to providers.gradleProperty("mod_description").get(),
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources.srcDir(generateModMetadata.map { it.outputs.files.singleFile })
}
neoForge.ideSyncTask(generateModMetadata)

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

fun getGeneratedPackageName() = "$group.generated"

fun getModAssetsDirPath() = "src/main/resources/assets/$modId"
fun getGenOutputDirPath(taskName: String) = "generated/$taskName/src/main/java"

val enUsResourcePath = "${getModAssetsDirPath()}/lang/en_us.json"

val generateLangKeys = registerKeyConstantsFromJsonFileTask(
    name = "generateLangKeys",
    inputFilePath = enUsResourcePath,
    outputClassName = "LangKeys",
    taskDescription = buildString {
        append("A generated object that represents the keys in `$enUsResourcePath` resource file,")
        appendLine()
        append("to avoid hardcoding the keys across the codebase, which is error-prone, inefficient, and less type-safe.")
        appendLine(); appendLine();
        append("**Note:** Breaking changes may occur. This approach is preferred over hardcoding keys, which can lead to runtime errors or crashes.")
    }
)

fun registerKeyConstantsFromJsonFileTask(
    name: String,
    inputFilePath: String,
    outputClassName: String,
    taskDescription: String
): TaskProvider<Task> {
    val task = tasks.register(name) {
        group = generationTaskGroup
        description = taskDescription

        val taskName = name

        val inputFile = layout.projectDirectory.file(inputFilePath)
        val outputDir = layout.buildDirectory.dir(getGenOutputDirPath(taskName))

        inputs.file(inputFile)
        outputs.dir(outputDir)

        val generatedPackageName = getGeneratedPackageName()

        // Required for Gradle configuration caching; using `modId`
        // directly inside `doLast` can cause the build to fail.
        // Required to fix "Configuration cache problems found in this build."
        val cachedModId = modId

        doLast {
            val file = inputFile.asFile
            if (!file.exists()) return@doLast

            fun parseKeys(file: File): Map<String, String> {
                val parser = JsonParser.parseString(file.readText())
                return parser.asJsonObject.entrySet().associate { (key, _) ->
                    val constName = key
                        // Remove mod id if present
                        .replace(".$cachedModId", "", ignoreCase = true)
                        // Convert camelCase to snake_case
                        .replace(Regex("([a-z])([A-Z])"), "$1_$2")
                        .replace(".", "_")
                        .uppercase()

                    constName to key
                }
            }

            val constants = parseKeys(file)

            val generatedConstVals = constants.map { (constName, key) ->
                "    public static final String $constName = \"$key\";"
            }

            val classFile = outputDir.get().asFile
                .resolve(generatedPackageName.replace('.', '/'))
                .apply { mkdirs() }
                .resolve("$outputClassName.java")
            classFile.parentFile.mkdirs()

            classFile.writeText(
                """
                |package $generatedPackageName;
                |
                |import org.jetbrains.annotations.ApiStatus;
                |
                |${
                    taskDescription
                        .lines()
                        .joinToString(separator = "\n/// ", prefix = "/// ")
                }
                |///
                |/// This file is fully generated by Gradle scripts. Do not modify directly, as all changes will be reverted.
                |/// Update the task `$taskName` in `build.gradle.kts` if needed.
                |@ApiStatus.Internal
                |public final class $outputClassName {
                |    private $outputClassName() {
                |    }
                |
                |${generatedConstVals.joinToString("\n")}
                |}
            """.trimMargin()
            )

            println("Generated `$outputClassName`: ${classFile.path}")
        }
    }
    return task
}

java.sourceSets.main.get().apply {
    java.srcDir(generateLangKeys.map { it.outputs.files.singleFile })
}

tasks.compileJava {
    dependsOn(generateLangKeys)
}

// The API JAR file includes only classes from the API package.

val apiPackage = "yesman/epicfight/api/**"
val apiJarClassifier = "api"

val apiJar by tasks.registering(Jar::class) {
    group = "build"
    archiveClassifier.set(apiJarClassifier)

    from(sourceSets.main.get().output) { include(apiPackage) }
}

val apiSourcesJar by tasks.registering(Jar::class) {
    group = "build"
    archiveClassifier.set("$apiJarClassifier-sources") // Important to use this suffix, to follow standards

    from(sourceSets.main.get().allSource) { include(apiPackage) }
}

artifacts {
    archives(apiJar)
    archives(apiSourcesJar)
}

fun extractCurrentVersionChangelog(): String? {
    val changelogFile = project.file("RELEASE_NOTES.md")
    val fullChangelogText = changelogFile.readText()

    // Extracts the current version changelog without the version heading 2 and "For Devs" heading 3.
    val versionSectionRegex =
        "(?s)## \\[$modVersion\\] - \\d{4}-\\d{2}-\\d{2}\\R(.*?)(?=\\R### For Devs|\\R## \\[.*?\\] |\\Z)"
    val matcher = Regex(versionSectionRegex).find(fullChangelogText) ?: return null

    val versionChangelog = matcher.groupValues[1]
    return versionChangelog
}

fun buildReleaseChangelog(currentVersionChangelog: String): String {
    return buildString {
        append(currentVersionChangelog)
        appendLine(); appendLine()
        append(
            """
    ### **Tested against:**
    - **NeoForge:** $neoforgeVersion
    - **Minecraft:** $mcVersion
    """.trimIndent()
        )
    }
}

publishMods {
    dryRun.set(false)

    val latestChangelog = extractCurrentVersionChangelog() ?: run {
        println("No matching changelog found for version $modVersion in RELEASE_NOTES.md. Publishing is skipped.")
        return@publishMods
    }
    val releaseChangelog = buildReleaseChangelog(latestChangelog)
    changelog.set(releaseChangelog)

    modLoaders.add(modLoader)
    type.set(STABLE)
    displayName.set(getFullModVersion())
    file.set(tasks.jar.get().archiveFile)
    additionalFiles.from(sourcesJar, apiJar, apiSourcesJar)

    curseforge {
        accessToken.set(providers.environmentVariable("CURSEFORGE_TOKEN"))
        projectId.set("405076")
        minecraftVersions.add(mcVersion)
        projectSlug.set("epic-fight-mod") // Required for Discord notification
    }

    modrinth {
        accessToken.set(providers.environmentVariable("MODRINTH_TOKEN"))
        projectId.set("vu3NZ5Ma")
        minecraftVersions.add(mcVersion)

        // Syncs the GitHub README with the Modrinth project description
        projectDescription.set(
            providers.fileContents(layout.projectDirectory.file("README.md")).asText
        )
    }

    discord {
        webhookUrl.set(providers.environmentVariable("DISCORD_WEBHOOK"))
        dryRunWebhookUrl.set(providers.environmentVariable("DRY_RUN_DISCORD_WEBHOOK"))
        username.set("Update Notification")
        avatarUrl.set("https://i.imgur.com/FrxDviN.png")
        content.set(
            changelog.map {
                "<@&1074034800849059930>\n# Epic Fight $modVersion is out!\n- **Minecraft version:** ${mcVersion}\n- **NeoForge version:** ${neoforgeVersion}\n$latestChangelog"
            }
        )

        style {
            look.set("MODERN")
            link.set("EMBED")
            thumbnailUrl.set("https://i.imgur.com/nI8xOCy.png")
        }
    }
}
