plugins {
    `java-library`
    id("net.neoforged.moddev").version("2.0.120")
    idea
    id("me.modmuss50.mod-publish-plugin").version("1.1.0")
}

tasks.named<Wrapper>("wrapper") {
    distributionType = Wrapper.DistributionType.BIN
}

val modVersion = providers.gradleProperty("mod_version").get()
val mcVersion = providers.gradleProperty("minecraft_version").get()
val neoforgeVersion = providers.gradleProperty("neo_version").get()
val modId = providers.gradleProperty("mod_id").get()
val modLoader = "neoforge"

version = modVersion
group = providers.gradleProperty("mod_group_id").get()

repositories {
    fun strictMaven(url: String, includeGroup: String, name: String? = null) {
        exclusiveContent {
            forRepository { maven { name?.let { this.name = it }; this.url = uri(url) } }
            filter { includeGroup(includeGroup) }
        }
    }
    flatDir { dir("libs") }

    strictMaven("https://cursemaven.com", "curse.maven", "CurseForge")
    strictMaven("https://api.modrinth.com/maven", "maven.modrinth", "Modrinth")

    // JEI
    strictMaven("https://maven.blamejared.com", "mezz.jei", "Jared")

    strictMaven("https://maven.architectury.dev", "dev.architectury", "Architectury")
    strictMaven("https://maven.latvian.dev/releases", "dev.latvian.mods", "Architectury")

    // Controlify, YACL
    strictMaven("https://maven.isxander.dev/releases", "dev.isxander", "IsXander")
}

base {
    archivesName = modId
    version = getFullModVersion()
}

fun getFullModVersion(): String = "${modVersion}-mc${mcVersion}-${modLoader}"

java {
    withSourcesJar()

    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

val sourcesJar by tasks.getting(Jar::class)

neoForge {
    version = neoforgeVersion

    parchment {
        mappingsVersion = providers.gradleProperty("parchment_mappings_version").get()
        minecraftVersion = mcVersion
    }

    runs {
        create("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            data()
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by NeoForge's data generators.
sourceSets.main {
    resources.srcDir(layout.projectDirectory.dir("src/generated/resources"))
}

configurations {
    val localRuntime by creating

    runtimeClasspath {
        extendsFrom(localRuntime)
    }
}

dependencies {
    val localRuntime by configurations.getting

    // JEI compatibility (optional)
    val jeiVersion = providers.gradleProperty("jei_version").get()
    compileOnly("mezz.jei:jei-${mcVersion}-common-api:${jeiVersion}")
    compileOnly("mezz.jei:jei-${mcVersion}-neoforge-api:${jeiVersion}")
    localRuntime("mezz.jei:jei-${mcVersion}-neoforge:${jeiVersion}")

    // Azurelib, Azurelib armor, Geckolib compatibility (optional)
    compileOnly("curse.maven:azurelib-817423:7084472")
    compileOnly("curse.maven:azurelib-armor-912767:7084466")
    compileOnly("curse.maven:geckolib-388172:6304958")

    // Iris, Sodium compatibility, compute shader compat (optional)
    compileOnly("curse.maven:irisshaders-455508:6661598")
    compileOnly("curse.maven:sodium-394468:6382651")

    // Werewolves, Vampirism compatibility, baking layer model for vampire and visibility fix when transform to the wolf (optional)
    compileOnly("curse.maven:werewolves-become-a-beast-417851:6538693")
    compileOnly("curse.maven:vampirism-become-a-vampire-233029:6544569")

    // Curios compatibility, baking curio models from curio slots (optional)
    compileOnly("curse.maven:curios-309927:6529130")

    // Player animator compatibility, emote fix (optional)
    compileOnly("curse.maven:playeranimator-658587:6024462")

    // KubeJS compatibility
    compileOnly("dev.latvian.mods:kubejs-neoforge:${providers.gradleProperty("kubejs_version").get()}")
    compileOnly("dev.latvian.mods:rhino-neoforge:${providers.gradleProperty("rhino_version").get()}")
    compileOnly("dev.architectury:architectury-neoforge:${providers.gradleProperty("architectury_version").get()}")

    // Libraries for tr7zw featured mods (optional, when you dependent your project on 3D Skin Layers or First-person)
    compileOnly("libs:TRansition:1.0.6")
    compileOnly("libs:TRender:1.0.7")

    // Skinlayer3d compatibility (optional)
    compileOnly("maven.modrinth:3dskinlayers:B7MZQ4xS")

    // First-person compatibility (optional)
    compileOnly("maven.modrinth:first-person-model:QWJDSZiH") // 2.5.0

    // Shoulder Surfing Reloaded compatibility (optional, uncomment the runtimeOnly to test the mod)
    compileOnly("curse.maven:shoulder-surfing-reloaded-243190:6993797") // API only
    //runtimeOnly "curse.maven:shoulder-surfing-reloaded-243190:6993795" // Full mod JAR file

    // Change "compileOnly" to "implementation" for testing in-game.
    compileOnly("dev.isxander:controlify:${providers.gradleProperty("controlify_version").get()}") {
        // Only need Controlify API, ignore the transitive dependencies (e.g, QuiltMC parsers)
        isTransitive = false
    }
}


val generationTaskGroup = "generation"

val generateModMetadata by tasks.registering(ProcessResources::class) {
    group = generationTaskGroup

    val replaceProperties = mapOf(
        "minecraft_version_range" to providers.gradleProperty("minecraft_version_range").get(),
        "neo_version_range" to providers.gradleProperty("neo_version_range").get(),
        "loader_version_range" to providers.gradleProperty("loader_version_range").get(),
        "mod_id" to modId,
        "mod_version" to modVersion,
        "mod_license" to providers.gradleProperty("mod_license").get(),
        "mod_name" to providers.gradleProperty("mod_name").get(),
        "mod_authors" to providers.gradleProperty("mod_authors").get(),
        "mod_description" to providers.gradleProperty("mod_description").get(),
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources.srcDir(generateModMetadata.map { it.outputs.files.singleFile })
}
neoForge.ideSyncTask(generateModMetadata)

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

publishMods {
    val readme = project.file("RELEASE_NOTES.md")
    val readmeContent = readme.readText()
    val pattern = "(?s)## \\[$modVersion\\] - \\d{4}-\\d{2}-\\d{2}\\R(.*?)(?=\\R### For Devs|\\R## \\[.*?\\] |\\Z)"
    val matcher = Regex(pattern).find(readmeContent)

    // No publishing without matching changelog
    if (matcher == null) {
        println("No matching changelog found for version $modVersion in RELEASE_NOTES.md. Publishing is skipped.")
        return@publishMods
    }

    // Extract the latest changelog without the header and API change part
    val latestChangelog = matcher.groupValues[1]

    // Test run to see the notification works well in discord
    dryRun.set(true)

    changelog.set(
        """
    **Tested against:**
    - **NeoForge:** $neoforgeVersion
    - **Minecraft:** $mcVersion
    """.trimIndent()
    )

    // The name of the mod loader
    modLoaders.add("neoforge")

    type.set(STABLE)

    displayName.set(getFullModVersion())

    file.set(tasks.jar.get().archiveFile)
    additionalFiles.from(sourcesJar)


    curseforge {
        accessToken.set(providers.environmentVariable("CURSEFORGE_TOKEN"))
        projectId.set("405076")
        minecraftVersions.add(mcVersion)
        projectSlug.set("epic-fight-mod")
    }

    modrinth {
        accessToken.set(providers.environmentVariable("MODRINTH_TOKEN"))
        projectId.set("vu3NZ5Ma")
        minecraftVersions.add(mcVersion)

        // Syncs the GitHub README with the Modrinth project description
        projectDescription.set(
            providers.fileContents(layout.projectDirectory.file("README.md")).asText
        )
    }
    // Discord webhook and notification settings
    discord {
        webhookUrl.set(providers.environmentVariable("DISCORD_WEBHOOK"))
        dryRunWebhookUrl.set(providers.environmentVariable("DRY_RUN_DISCORD_WEBHOOK"))
        username.set("Update Notification")
        avatarUrl.set("https://i.imgur.com/FrxDviN.png")
        content.set(
            changelog.map {
                "<@&1074034800849059930>\n# Epic Fight $modVersion is out!\nMinecraft version: ${mcVersion}\nNeoForge version: ${neoforgeVersion}\n$latestChangelog"
            }
        )

        style {
            look.set("MODERN")
            link.set("EMBED")
            thumbnailUrl.set("https://i.imgur.com/nI8xOCy.png")
        }
    }
}
