org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric Properties — check at https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=fabric-21.17.3
group_id=yesman.epicfight
mod_id=epicfight
display_name=Epic Fight
license=Code: GPL-3.0; Assets: All Rights Reserved
authors=Yesman, Gui, Asan, Wayfarer(aka squoshi), Fori, Ellet, MikihinaSann
description=Adds complex game mechanics and fighting styles to your gameplay, while making Minecraft more Souls-like
issue_tracker=https://github.com/Epic-Fight/epicfight/issues
source_code=https://github.com/Epic-Fight/epicfight/
display_url=https://epicfight-docs.readthedocs.io
credits=https://epicfight-docs.readthedocs.io/Misc/credits/

# Dependencies
fabric_api_version=0.116.15+1.21.1

# Compat mods (CurseMaven file IDs)
azurelib_file_id=8367231
betterthirdperson_file_id=5439141
trinkets_file_id=5534317
fgm_file_id=5478368
firstperson_file_id=8294226
geckolib_file_id=8350058
iris_file_id=8242801
jei_file_id=8678370
playeranimator_file_id=7389821
shouldersurfing_file_id=8596429
simplytooltips_file_id=8715135
skinlayers_file_id=8274818
sodium_file_id=8591793
