#version 460 core

layout(local_size_x = 128) in;

// Dynamic Input Buffer
layout(std430, binding = 0) readonly buffer PoseBuffer {
    mat4 poses[];
};

// Static Buffer
layout(std430, binding = 1) readonly buffer VertexBuffer {
    struct {
        float px,py,pz,nx,ny,nz;
        int jts,jte; // 骨骼&权重在池子中的范围
    } vertices[];
};

layout(std430, binding = 2) readonly buffer JointsPool {
    int joints[];
};

layout(std430, binding = 3) readonly buffer WeightsPool {
    float weights[];
};


// Output Buffer
layout(std430, binding = 4) writeonly buffer OutputPositionBuffer {
    float out_pos[];
};

layout(std430, binding = 5) writeonly buffer OutputNormalBuffer {
    uint out_normal[];
};

layout(std430, binding = 6) writeonly buffer OutputColorBuffer {
    vec4 out_color[];
};

layout(std430, binding = 7) writeonly buffer OutputUV1Buffer {
    uint out_uv1[];
};

layout(std430, binding = 8) writeonly buffer OutputUV2Buffer {
    uint out_uv2[];
};

/**layout(std430, binding = 9) readonly buffer UVBuffer {
    float uv[];
};

layout(std430, binding = 10) writeonly buffer OutputVertBuffer {
    struct {
        float x, y, z;
        float r,g,b,a;
        float u,v;
        uint uv1, uv2;
        int nor;
    } out_vert[];
};*/

layout(location=0) uniform vec4 colorIn;
layout(location=1) uniform uint uv1In;
layout(location=2) uniform uint uv2In;
layout(location=3) uniform mat4 partTransform;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= vertices.length()) return; // check.

    vec4 pos = vec4(vertices[idx].px, vertices[idx].py, vertices[idx].pz, 1.0);
    vec4 norm = vec4(normalize(vec3(vertices[idx].nx, vertices[idx].ny, vertices[idx].nz)), 0.0);

    vec4 finalPos = vec4(0);
    vec4 finalNormal = vec4(0);

    for (int i = vertices[idx].jts; i < vertices[idx].jte; ++i) {
        if (weights[i] > 0.0) {
            mat4 boneMat = poses[joints[i]] * partTransform;

            finalPos += (boneMat * pos) * weights[i];
            finalNormal += boneMat * norm * weights[i];
        }
    }

    //finalPos = modelView * finalPos;
    //finalNormal = mat3(modelView) * finalNormal;
    out_pos[idx * 3] = finalPos.x;
    out_pos[idx * 3 + 1] = finalPos.y;
    out_pos[idx * 3 + 2] = finalPos.z;

    out_normal[idx] = packSnorm4x8(vec4(normalize(finalNormal.xyz), 0.0));

    out_color[idx] = colorIn;
    out_uv1[idx] = uv1In;
    out_uv2[idx] = uv2In;

   /** out_vert[idx].x = finalPos.x;
    out_vert[idx].y = finalPos.y;
    out_vert[idx].z = finalPos.z;

    out_vert[idx].r = colorIn.r;
    out_vert[idx].g = colorIn.g;
    out_vert[idx].b = colorIn.b;
    out_vert[idx].a = colorIn.a;

    out_vert[idx].u = uv[idx*2];
    out_vert[idx].v = uv[idx*2+1];

    out_vert[idx].uv1 = uv1In;
    out_vert[idx].uv2 = uv2In;

    out_vert[idx].nor = packSnorm4x8(vec4(normalize(finalNormal.xyz), 0.0));*/
}