name: Code Quality Checks

on: [ push, pull_request ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check IntelliJ Formatting
        uses: sidhant92/intellij-format-action@v1
        with:
          tool_name: 'IntelliJ Diff'
          github_token: ${{ secrets.github_token }}
          fail_on_changes: true
          path: '.'
          file_mask: '*.java'
